version: 2

models:
  - name: dim_promos
    description: Promo details applicable to purchases, including discount & status.
    columns:
      - name: promo_id
        description: Primary key for this table.
        tests:
          - unique
          - not_null
      - name: discount
        descripiton: "The percentage applied as discount with the promotion"
        tests:
        - not_null

  - name: int_daily_promos_used
    description: Aggregation of orders with promo codes used
    columns:
      - name: promo_id
        description: Primary key for this table
        tests:
        - not_null

  - name: int_user_order_facts
    description: Identification of repeat users
    columns:
      - name: user_id
        description: Primary key for this table
        tests:
        - not_null       

  - name: fact_user_orders
    description: Orders per user
    columns:
      - name: user_id
        description: Primary key for this table
        tests:
        - unique
        - not_null
      - name: user_created_at
        description: Timestamp of user creation
        tests:
        - not_null
      - name: date_first_order
        description: Interval to the user first order
        tests: 
        - not_null
